name = "j-madamis"
compatibility_date = "2024-08-18"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "madamis-db"
database_id = "8c7855a5-36c2-4d5d-b027-c1ee7fad2436"
preview_database_id = "DB"